.TH RNOTE 1 "2019-07-27" "rnote manual page" "rnote manual page"

.SH NAME
rnote

.SH SYNOPSIS
.B rnote
[\fIOPTION\fR]

.SH DESCRIPTION
\fBrnote\fR is a software to take notes in a simple and convenient way.
.SH OPTIONS
\fB-h, --help\fR
.br
	show help
.PP
\fB-v, --version\fR
.br
	show version information

.SH AUTHORS
Written by Robert Imschweiler
